### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [VladyslavIstomin/kottans-js-2016#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by sudodoki** [comment]
Don't see any screenshot

**Comment by VladyslavIstomin** [comment]
Sorry. I`ve already finished the task

**Comment by VladyslavIstomin** [comment]
https://github.com/VladyslavIstomin/kottans-js-2016/tree/master/week01/Git

2016-05-25 0:29 GMT+03:00 Джон, просто Джон notifications@github.com:

**Comment by sudodoki** [comment]
LGTM
